/**rxconst */
export const ADD_DRIVE_ASSIGNMENT = 'ADD_DRIVE_ASSIGNMENT';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PASSWORD_CONFIRM = 'SET_PASSWORD_CONFIRM';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const TOGGLE_SHOW_PASSWORD = 'TOGGLE_SHOW_PASSWORD';
export const UPDATE_USERINFO = 'UPDATE_USERINFO';
export const CLEAR_AUTH_INFO = 'CLEAR_AUTH_INFO';

export const CHECK_AUTHENTICATION = 'CHECK_AUTHENTICATION';
export const SET_ACTIVE_FIELD = 'SET_ACTIVE_FIELD';
export const SET_DRIVEMEMO_INPUT = 'SET_DRIVEMEMO_INPUT';
export const SUBMIT_DRIVEMEMO = 'SUBMIT_DRIVEMEMO';
export const SET_DRIVEMEMO_DATETIME = 'SET_DRIVEMEMO_DATETIME';
export const TOGGLE_DRIVEASS_MODAL = 'TOGGLE_DRIVEASS_MODAL';
export const CHANGE_INVOICE_TARGET = 'CHANGE_INVOICE_TARGET';
export const CHANGE_INVOICE_CLIENT = 'CHANGE_INVOICE_CLIENT';
export const RESET_ACTIVEFIELD_INFO = 'RESET_ACTIVEFIELD_INFO';
export const TOGGLE_DRIVEASS_EDIT = 'TOGGLE_DRIVEASS_EDIT';
export const DRIVEASS_EDIT_TARGET = 'DRIVEASS_EDIT_TARGET';
export const UPDATE_EDIT_TARGET = 'UPDATE_EDIT_TARGET';
export const SAVE_DRIVEASS_EDIT = 'SAVE_DRIVEASS_EDIT';
export const DELETE_DRIVEASS = 'DELETE_DRIVEASS';
export const TOGGLE_DRIVEMEMO_DRAFT = 'TOGGLE_DRIVEMEMO_DRAFT';
export const DRIVEMEMO_UPDATE = 'DRIVEMEMO_UPDATE';
// export const LOGIN_USERNAME = 'LOGIN_USERNAME';
// export const LOGIN_PASSWORD = 'LOGIN_PASSWORD';.-,
